# Site settings
name: Ibrahim Oladepo
title: Ibrahim Oladepo | Design Engineer
description: Building neurotechnologies, designing circuits, and making things work
url: https://ibrahimo.github.io/
baseurl: ''
email: oladepoibro@gmail.com
cover: https://ibrahimo.github.io/img/og.png  # TODO: change to my og image
logo: https://ibrahimo.github.io/img/logo/ib_logo_small.png
resume: https://ibrahimo.github.io/resume.pdf
social:
  - title: email
    url: mailto:oladepoibro@gmail.com
  - title: twitter
    url: https://twitter.com/ibrahimoladepo
  - title: instructables
    url: https://www.instructables.com/member/OladepoI/?publicPreview=true
  - title: medium
    url: https://medium.com/@IbrahimOladepo
  - title: github
    url: https://github.com/ibrahimoladepo
  - title: linkedin
    url: https://www.linkedin.com/in/ibrahim-oladepo-90779284/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'
  - 'vendor'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
